spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/advocacia-2tdspg?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

